// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrmyylutphmiinoccpfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybXl5bHV0cGhtaWlub2NjcGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzI5NTcsImV4cCI6MjA3MDY0ODk1N30.SoMt_lViCDEhG9djHQQeZ2xQgPZWZ_e_vjTR7Y7ekpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});